version: '3'

services:

  www:
    depends_on:
      - db
    image: nimmis/apache-php5
    container_name: 0-php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8030:80"

  db:
    image: mysql:5.7.22
    container_name: 1-mysql
    environment:
      MYSQL_DATABASE: myDB
      MYSQL_USER: fancooler
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234root
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 2-phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: fancooler
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234root
    ports:
      - "80:80"

volumes:
  db: